name: Build ZXBasicStudio

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'

      - name: Build solution
        run: dotnet build ZXBasicStudio.sln --configuration Release

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ZXBasicStudio
          path: |
            **/bin/Release/
